version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.10.1
    
    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          - v2-dependencies-

      - run:
          name: Install pandoc
          command: |
                    sudo apt-get update 
                    wget https://github.com/jgm/pandoc/releases/download/2.14.1/pandoc-2.14.1-1-amd64.deb
                    sudo dpkg -i pandoc-2.14.1-1-amd64.deb

      - run:
          name: Install java
          command: |
                    sudo apt-get install default-jdk
          
      - run:
          name: Install tex
          command: |
                    sudo apt-get install -y texlive
                    sudo apt-get install -y texlive-latex-extra
                    sudo apt-get install -y dvipng
          
      - run:
          name: Install 7z, unrar
          command: |
                    sudo apt-get install -y p7zip-full
          
      - run:
          name: Install InkScape
          command: |
                    sudo apt-get install -y inkscape
          
      - run:
          name: Install graphviz
          command: |
                    sudo apt-get install -y graphviz
          
      - run:
          name: Install libproj
          command: |
            sudo apt-get install -y libgeos-dev libproj-dev proj-data graphviz

      - run:
          name: Install standard libraries
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install scipy matplotlib numpy cython pandas

      - run:
          name: Install pyproj, shapely, cartopy
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install pyproj
            pip3 uninstall -y shapely
            pip3 install --no-binary shapely shapely
            pip3 install cartopy

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install mplfinance

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            export PYTHONPATH=src
            python setup.py unittests

      - run:
          name: wheel
          command: |
            . venv/bin/activate
            export PYTHONPATH=src
            python setup.py bdist_wheel
            mkdir -p test-reports/dist
            cp dist/*.whl test-reports/dist

      #- run:
      #    name: documentation
      #    command: |
      #      . venv/bin/activate
      #      export PYTHONPATH=src
      #      python setup.py build_sphinx
            
      #- run:
      #    name: copy documentation
      #    command: |
      #      mkdir -p test-reports/doc
       #     zip -r -9  test-reports/doc/documentation_html.zip _doc/sphinxdoc/build/html
            
      - store_artifacts:
          path: test-reports
          destination: test-reports